app:
  name: "telegram-bot"
  environment: "dev"

server:
  port: "8990"
  host: "localhost"
  read_timeout: 30
  write_timeout: 30
  fasthttp:
    maxConnsPerHost: 100 # concurrent worker number
    maxIdleConnDuration: 30
    readTimeout: 5
    writeTimeout: 5

telegram:
  port: ":8080"
  timeout: "10s"
  group: -1001999851882,-1001856345480
  monitored_groups:
    - -1001999851882 # main chat group
    - -1001856345480 # vip chat group
    - -1002217128790 # test chat group
  monitored_topics:
    - 39757
    - 39760
    - 43371
    - 39762
    - 4718
  command_patterns:
    - "^/[a-zA-Z]+"
    - "^![a-zA-Z]+"
    - "^\\.[a-zA-Z]+"
    - "^https?://"
    - "(?i)www\\.[a-z0-9]"
    - "(?i)http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+"
    - "t\\.me/[a-zA-Z0-9_]+"
  send_warning: true
  warning_duration: 30

exchange:
  bitget:
    api_key: "" # add key value in .env
    secret_key: "" # add key value in .env
    passphrase: "" # add key value in .env
    baseUrl: "https://api.bitget.com"
    customer_list: "/api/broker/v1/agent/customerList"
    customer_trade_volume: "/api/broker/v1/agent/customerTradeVolumnList"

database:
  host: localhost
  port: 3306
  user: user
  password: pass
  database: "omcc"
  max_idle_connections: 10
  max_open_connections: 100
  max_lifetime: "1h"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
